FROM postgres:16-alpine

ENV POSTGRES_DB=mydatabase
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password

COPY db/migrations/V1__initial_schema.sql /docker-entrypoint-initdb.d/
COPY db/data/seed_data.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
